spring:
  application:
    name: PostManTestApi
  profiles:
    group:
      "local": "testdb"
      "dev": "testdb"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: TRACE
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



---
spring:
  config:
    activate:
      on-profile: "testdb"

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      data-locations: "classpath*:/data.sql"
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

jpa:
  hibernate:
    ddl-auto: create

  properties:
    hibernate:
      format_sql: true
