###

# curl -X POST http://localhost:8080/members/login
#    -H "Content-Type: application/json"
#    -d '{
#          "nickName": "testUser",
#          "password": "testPassword"
#        }'
POST http://localhost:8080/members/login
Content-Type: application/json

{
  "nickName": "testUser",
  "password": "testPassword"
}

###

# curl -X POST http://localhost:8080/members/join
#    -H "Content-Type: application/json"
#    -d '{
#          "name": "Test User",
#          "password": "testPassword",
#          "nickName": "testUser"
#        }'
POST http://localhost:8080/members/join
Content-Type: application/json

{
  "name": "Test User",
  "password": "testPassword",
  "nickName": "testUser"
}

###

# curl -X PUT http://localhost:8080/members/update
#    -H "Content-Type: application/json"
#    -d '{
#          "id": 1,
#          "name": "Updated User",
#          "password": "newPassword",
#          "nickName": "updatedUser"
#        }'
PUT http://localhost:8080/members/update
Content-Type: application/json

{
  "id": 1,
  "name": "Updated User",
  "password": "newPassword",
  "nickName": "updatedUser"
}

###

# curl -X DELETE http://localhost:8080/members/leave
#    -H "Content-Type: application/json"
#    -d '{
#          "id": 1
#        }'
DELETE http://localhost:8080/members/leave
Content-Type: application/json

{
  "id": 1
}

###

# curl -X POST http://localhost:8080/members/login
#    -H "Content-Type: application/json"
#    -d '{
#          "nickName": "nonExistentUser",
#          "password": "testPassword"
#        }'
POST http://localhost:8080/members/login
Content-Type: application/json

{
  "nickName": "nonExistentUser",
  "password": "testPassword"
}

###

# curl -X POST http://localhost:8080/members/login
#    -H "Content-Type: application/json"
#    -d '{
#          "nickName": "testUser",
#          "password": "wrongPassword"
#        }'
POST http://localhost:8080/members/login
Content-Type: application/json

{
  "nickName": "testUser",
  "password": "wrongPassword"
}

###

# curl -X POST http://localhost:8080/members/join
#    -H "Content-Type: application/json"
#    -d '{
#          "name": "Another User",
#          "password": "testPassword",
#          "nickName": "testUser"  # 이미 존재하는 닉네임
#        }'
POST http://localhost:8080/members/join
Content-Type: application/json

{
  "name": "Another User",
  "password": "testPassword",
  "nickName": "testUser"
}

###

# curl -X PUT http://localhost:8080/members/update
#    -H "Content-Type: application/json"
#    -d '{
#          "id": 9999,  # 존재하지 않는 ID
#          "name": "Updated User",
#          "password": "newPassword",
#          "nickName": "updatedUser"
#        }'
PUT http://localhost:8080/members/update
Content-Type: application/json

{
  "id": 9999,
  "name": "Updated User",
  "password": "newPassword",
  "nickName": "updatedUser"
}

###

# curl -X PUT http://localhost:8080/members/update
#    -H "Content-Type: application/json"
#    -d '{
#          "id": 1,  # 존재하는 ID
#          "name": "Updated User",
#          "password": "newPassword",
#          "nickName": "existingNickName"  # 이미 존재하는 닉네임
#        }'
PUT http://localhost:8080/members/update
Content-Type: application/json

{
  "id": 1,
  "name": "Updated User",
  "password": "newPassword",
  "nickName": "existingNickName"
}

###




# curl -X DELETE http://localhost:8080/members/leave
#    -H "Content-Type: application/json"
#    -d '{
#          "id": 9999  # 존재하지 않는 ID
#        }'
DELETE http://localhost:8080/members/leave
Content-Type: application/json

{
  "id": 9999
}

###

