
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: local

    steps:
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 400 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "ps -ef | grep PostManTestApi"
        rm -f private_key.pem
  test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run Newman tests on AWS
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ./usingpostman; cat ./runNewman_memeberApisTest.sh; ./runNewman_memeberApisTest.sh"
          rm -f private_key.pem
